Disable Docker Hub upload for untagged builds

diff --git a/bin/push-docker-image b/bin/push-docker-image
--- a/bin/push-docker-image
+++ b/bin/push-docker-image
@@ -1,19 +1,24 @@
 #!/usr/bin/env bash
 
 # Run on Travis CI after a succesful build
-# Uploads docker image to Docker Hub, tagged with supplied package version
+# Uploads docker image to Docker Hub
+# Feature only enabled on master with valid build tag
 
 set -e +o pipefail
 
-if [[ "$1" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
+if [ -z "$TRAVIS_BRANCH" ] || [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ] || [ -z "$DOCKER_IMAGE" ]; then
+  echo "ERROR: Missing environment variables"
+  exit 1
+fi
+
+if [[ "$TRAVIS_TAG" =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
     if [ "$TRAVIS_BRANCH" == "master" ]; then
         docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
-        export DOCKER_IMAGE_TAG=$DOCKER_IMAGE:$1
+        export DOCKER_IMAGE_TAG=$DOCKER_IMAGE:${TRAVIS_TAG:1}
         docker tag $DOCKER_IMAGE $DOCKER_IMAGE_TAG
         docker push $DOCKER_IMAGE_TAG
     fi
 else
-    echo "Invalid parameter: $1"
-    echo "Usage: push-docker-image <major.<minor>.<patch>"
+    echo "Pushing build to Docker Hub is disabled on '$TRAVIS_BRANCH' branch with '$TRAVIS_TAG' build tag"
     exit 1
 fi
